# Generated by Django 5.1.3 on 2024-12-02 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosDueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('num_mascotas', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'datos_dueno',
            },
        ),
        migrations.CreateModel(
            name='DatosMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mascota', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=50)),
                ('nombre_mascota', models.CharField(max_length=255)),
                ('edad', models.PositiveIntegerField()),
                ('tamano', models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=20)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datosdueno')),
            ],
            options={
                'db_table': 'datos_mascota',
            },
        ),
    ]
