# Generated by Django 5.1.3 on 2024-12-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoria_pregunta_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='pregunta',
            unique_together={('categoria', 'pregunta_texto')},
        ),
    ]
