# Generated by Django 5.1.3 on 2024-12-08 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('pregunta', 'respuesta_texto')},
        ),
    ]
